### ISSUE TITLE
error when run-android

### ISSUE THREAD

**Issue by wzy535** [tranquangvu/react-native-uploader#1]
Hello,I got this errors,Could you help me?
FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':app'.
  
  > Cannot evaluate module RNFileTransfer : Configuration with name 'default' not found.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by tranquangvu** [comment]
Hi @wzy535 

Reason of this error because my bad README.md. I'm sorry about that. I have updated README.md, so you can try it again. Hope it can help you.

This module is a cover for my requirements of my project. For the original module, you can reference https://github.com/aroth/react-native-uploader (only iOS support) or https://github.com/g6ling/react-native-uploader (iOS and Android support. Note: Wrong README.md. lol)

**Comment by SunboyGo** [comment]
Android can run，but can not upload

**Comment by SunboyGo** [comment]
README.md Still wrong ，MainApplication.java  not MainActivity.java

**Comment by tranquangvu** [comment]
@songbaogang 
- Remove react-native-uploader in node_modules and package.json. After try this to install again: 
  `npm install https://github.com/tranquangvu/react-native-uploader.git --save`
- I have just updated the README.md

**Comment by wzy535** [comment]
hi, I modifed as README.md, but got errors:
 What went wrong:
A problem occurred configuring project ':app'.

> Cannot evaluate module react-native-uploader : Configuration with name 'default' not found.
> any ideas?

**Comment by SunboyGo** [comment]
@tranquangvu 
I tried the method you said, still can not upload, tips:

`D/ImageUploadAndroid: java.lang.NullPointerException: com.ele Attempt to invoke virtual method'char[] java.lang.String.toCharArray on () 'a null object reference`

**Comment by tranquangvu** [comment]
@wzy535 
Check your MainApplication.java. It must import FileTransferPackage and new FileTransferPackage() in getPackages().

```
import com.burlap.filetransfer.FileTransferPackage;
...
private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
  ....
  @Override
  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
      ...
      new FileTransferPackage()
    );
  }
}
```

**Comment by tranquangvu** [comment]
@wzy535 , @songbaogang 
I have just create a demo for react-native-uploader. It can be run in Android and iOS. You can check it [https://github.com/tranquangvu/react-native-uploader-demo](https://github.com/tranquangvu/react-native-uploader-demo)

Hope it can help you.

Note: This project i have follow all step in README.md.

**Comment by vjtc0n** [comment]
@tranquangvu Thank you for your lib, and your Demo, too. It helped me alot.
By the way, do you still use this server: 'https://posttestserver.com/' ? ( I found it inside your demo)

## If it has no secret, I wish you could push it on Github :) 

Cảm ơn bạn trangquangvu đã cover lại 1 lib rất hữu ích.
Nếu như phần server không có bí mật về công việc, mình mong muốn bạn có thể chia sẻ với cộng đồng ^^.
Mình mới học RN được 2 tuần nên thiếu nhiều kinh nghiệm.
Cảm ơn đã lắng nghe.

**Comment by tranquangvu** [comment]
hi @vjtc0n, 

The server https://posttestserver.com/ is free online test server for post request. I'm not implement it. lol :)

**Comment by amitbravo** [comment]
I find out that when we modify MainApplication.java file , we use comma , between where calling classes as 

new FileTransferPackage(),
          new MainReactPackage()

otherwise built failed many times.
