### ISSUE TITLE
Cannot read property of 'upload' of undefined

### ISSUE THREAD

**Issue by naawdawg** [tranquangvu/react-native-uploader#4]
When trying to run this code, I get the error "Cannot read property of 'upload' of undefined" when RNUploader.upload(. . .) executes. Any reason why?

**Comment by tranquangvu** [comment]
@naawdawg Maybe you forgot `import RNUploader from 'react-native-uploader'`. You can follow this example https://github.com/tranquangvu/react-native-uploader-demo
